services:
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://superset:superset@db/superset
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/superset_config.py
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: superset_db
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - superset_db_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: superset_redis

volumes:
  superset_db_volume:
